### PR TITLE
inference runs on CPU if no GPU available

### PR DESCRIPTION
**Pull request by kemaleren**
I wanted to test this model on a device with no GPU. Even though it is much slower and would not be a good idea in production, for testing small images it still runs in a reasonable amount of time.

### CODE REVIEW

**Comment by Parskatt** [comment]
I think it's probably better practice to have device as inputs to functions/properties of nn.Modules rather than defined outside the local scope, but that's a minor issue.

**Comment by kemaleren** [comment]
I thought so too, but the PyTorch blog has a section on writing device-agnostic code, that that's what they recommended: https://pytorch.org/blog/pytorch-0_4_0-migration-guide/#writing-device-agnostic-code

**Comment by kemaleren** [comment]
Also I'm sure there's things that still won't work. If they need to be fixed I can do that. I made these changes to get the `demo_match.py` script working.

**Comment by Parskatt** [comment]
I'll merge it and fix any issues later :p

**Pull request merged**
